### ISSUE TITLE
Which is the config directory?

### ISSUE THREAD

**Issue by ekkis** [leadstoloyals/node-agcod#5]
the README states:

> Create a development.json, sandbox.json and production.json in the config directory that looks like example.json.

so I am to create a file in the "config" directory.  which is the config directory? the one in `node_modules/node-agcod` (methinks not)? can we amend the README to be more clear?

**Comment by christiaanwesterbeek** [comment]
It's the config directory that already exists, directly in the root where `example.json` is in.

**Comment by christiaanwesterbeek** [comment]
On second thought, you're right, this is ambiguous. When node-agcod is installed as a dependency, its config dir is inside node_modules/node-agcod, but that's not where you need to add the json files. It's only where an example.json is kept.

You need to create a config dir in the root of your own repo and add the json files there.

**Comment by ekkis** [comment]
mich besser. thank you
